version: '2'

services:

  app:
    build:
      context: ./build/app
      dockerfile: ${app_dockerfile}
      args:
        - LOG_ERROR=${log_error}
        - LOG_ACCESS=${log_access}
        - MEMORY_LIMIT=${memory_limit}
        - POST_MAXSIZE=${post_maxsize}
        - UPLOAD_MAX_FILESIZE=${upload_max_filesize}
        - DATE_TIMEZONE=${date_timezone}
    ports:
      - 9000
    volumes:
      - ./data/passbolt/:/var/www/passbolt
    environment:
      - ADMIN_USERNAME=${admin_username}
      - ADMIN_FIRSTNAME=${admin_firstname}
      - ADMIN_LASTNAME=${admin_lastname}
      - MYSQL_HOST=db
      - MYSQL_DATABASE=${mysql_database}
      - MYSQL_USER=${mysql_user}
      - MYSQL_PASSWORD=${mysql_password}
      - HOST_NAME=${virtual_hosts}

  db:
    image: mysql:5.7.16
    volumes:
      - /var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${mysql_root_password}
      - MYSQL_DATABASE=${mysql_database}
      - MYSQL_USER=${mysql_user}
      - MYSQL_PASSWORD=${mysql_password}
    command: [--character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci]

  proxy:
    image: nginx:stable-alpine
    ports:
      - 80
    volumes_from:
      - app
    volumes:
      - ./config/app/app.conf:/etc/nginx/nginx/nginx.conf
    environment:
      - VIRTUAL_HOST=${virtual_hosts}
    networks:
      - default
      - ambassador

networks:
  default:
  ambassador:
    external:
      name: ambassador
